### ISSUE TITLE
Raspberry Pi 1 works with `/dev/i2c-0`

### ISSUE THREAD

**Issue by ankur22** [pimoroni/scd4x-python#4]
https://github.com/pimoroni/scd4x-python/blob/43e559128f5662e579af5acef911fb36c9ead65b/library/scd4x/__init__.py#L41

When I run the basic example i get the following:

```
(env) pi@raspberrypi-1:~/waterer $ python3 test_co2.py
Traceback (most recent call last):
  File "test_co2.py", line 6, in <module>
    device = SCD4X(quiet=False)
  File "/home/pi/waterer/env/lib/python3.7/site-packages/scd4x/__init__.py", line 41, in __init__
    self.bus = SMBus(1)
  File "/home/pi/waterer/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/home/pi/waterer/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
```

On my raspberry pi 1, this needs to be `self.bus = SMBus(0)` (/dev/i2c-0). I'm not 100% sure why that is (obviously something is missing or different on the hardware as compared to later raspberry pis). Some details about this here: http://wiki.erazor-zone.de/wiki:linux:python:smbus:doc.

**Comment by ageeandakeyboard** [comment]
Hi 
Yes you are correct the I2C bus got move from 0 to 1 when the raspberry pi two was released.
We did use to have a couple of lines that checked the raspberry pi version when the script was run.

We dropped it for newer products when the new raspberry pis came out.

Nowadays the I2C-0 bus is used for speaking with HATs id chip and the pi camera and not normally exposed for the user. 

Hope that helps
Regards
Gee
